# List possibilities after an ambiguous completion.
set autolist
# Enable color display for the builtin ls-F and pass --color=auto to ls
set color
set complete = igncase
set prompt = "%{\e[32m%}`hostname -s` %{\e[36m%}%c%{\e[0m%} "

setenv GREP_OPTIONS "--color=auto"
setenv LC_CTYPE en_US.UTF-8
setenv LC_ALL en_US.UTF-8

# Setting the full path of our dotfiles directory automatically.
set DOTFILES_CSHRC_PATH = `readlink ~/.cshrc`; set OLD_DIR = `pwd`
cd ${HOME}; cd `dirname ${DOTFILES_CSHRC_PATH}`/../; setenv DOTFILES `pwd`; cd ${OLD_DIR}
unset DOTFILES_CSHRC_PATH; unset OLD_DIR

# Load common environment variables setting such as EDITOR, PATH and so on.
source ${DOTFILES}/csh/env.csh

# Load common alias.
source ${DOTFILES}/csh/alias.csh

# Put local runtime configurations in ~/.local.cshrc, they'll stay out of your main dotfiles
# repository (which maybe public on the internet, like this one). Anything can be done safely,
# because this is the last runtime configuration file current shell will load.
if (-f ~/.local.cshrc) then
    source ~/.local.cshrc
endif
